### ISSUE TITLE
Comparison with move_base

### ISSUE THREAD

**Issue by Piroro-hs** [cogsys-tuebingen/gerona#11]
Hi. This looks cool! 
It would be great if you'd add a brief summary of comparison of this and move_base.

**Comment by zhengzh** [comment]
I started to learn this project a few days ago, I think it is a very awesome project. According to their paper, move base has some major limitations:

> 1. The framework is meant for only differential drives and holonomic wheeled robots.
> 2. It requires a planar laser mounted on the robot, needed for map building and localization.
> 3. It performs best on robots that are nearly square or circular, and it may have difficulties with large rectangular robots in narrow spaces.

**Comment by Gohus** [comment]
Hi! Thank you for your feedback and sorry for such a delay in the answer!
The main differences to move_base are explained in the introduction of our [GeRoNa paper](
https://rdcu.be/barrQ).
