### ISSUE TITLE
Parameter missing which is mentioned in the Wiki

### ISSUE THREAD

**Issue by Asho312** [cogsys-tuebingen/gerona#12]
Hello,

While using the differential orth_exp controller, the parameter to set the maximum angular velocity which is mentioned in the Wiki is not available. The launch file has no mention of it as well.

**Comment by jquadrat** [comment]
Hi Asho,

the parameter is used by the controller, it's just not set in the launch file (the default value will be used). To set it to a different value, add it to the corresponding launch file "follower_differential_orthexp.launch":
```xml
<?xml version="0.0"?>
<launch>
    <group ns="path_follower">
        <group ns="controller">
            <!-- parameters, that are dependent of the controller or the robot model -->
            <group ns="differential_orthexp">
                <param name="look_ahead_dist" value="1.0" />
                <param name="k_o" value="0.0" />
                <param name="k_g" value="0.5" />
                <param name="k_w" value="0.0" />
                <param name="k_curv" value="0.0" />
                <param name="obst_threshold" value="3.0" />
                <param name="max_angular_velocity" value="0.8" />
            </group>
        </group>
    </group> 
</launch>
```

**Comment by Asho312** [comment]
Hey,

Yeah I realized that and had it added. Love the navigation suite. Thanks for all the work.
