### ISSUE TITLE
HBZ controller not working in backwards

### ISSUE THREAD

**Issue by mardom95** [cogsys-tuebingen/gerona#13]
Hello ! And thanks in advance for this navigation suite.

I have tested several controllers and found that when using HBZ controller and the plan is backwards, the robot behaves incorrectly. It keeps oscillating and moving counter-sense from the initial point of the path. 

When planning forwards works fine, and the vehicle is differential driven. 

Note: robot must perform a 180 degree rotation initially when driving backwards, dont know if that can influence considering clamp limits.

Regards!
Mario

**Comment by mardom95** [comment]
Forgot, vehicle is differential drive.

**Comment by mardom95** [comment]
Hello,

After some experiments i found that changing the line 

delta_ = MathHelper::AngleClamp(-gerDirSign()*opt_.theta_a()*tanh(ye_));

to delta_ = MathHelper::AngleClamp(-opt_.theta_a()*tanh(ye_));

solved the issue, at least, if oriented in backward sense to the path, the robot converges to trajectory. Now it works in backwards and forwards.

Regards

**Comment by Gohus** [comment]
Hello @mardom95, thank you for your feedback! And I am sorry for such a late reply.
You are right, reverse driving was problematic, and now the new version is available (and yes, your change in the code for HBZ was good!).
Cheers!
