### ISSUE TITLE
Angular_velocity variable always at 0 for HBZ controller

### ISSUE THREAD

**Issue by DomBaril** [cogsys-tuebingen/gerona#14]
Hi,

First of all, thank you for this great work. I am starting to use the framework to control robots that we use here in Norlab of Laval University, Canada. I love the work you are doing!

I managed to get the HBZ controller working on one of our other robots in gazebo. I only have a small problem. The angular_vel variable, which defines the measured angular velocity of the robot always remains at 0 in my lab. I print it in the robotcontroller_kinematic_HBZ.cpp file and it never changes. This seems to have an impact on the output. Is the problem only located on my computer? In this case, maybe I have broken the code by using it.

Thanks in advance for your help!
Dominic

**Comment by DomBaril** [comment]
For now, I correct this issue by adding this line at  #158: 

angular_vel_ = pose_tracker_->getVelocity().angular.z;

This line is used for example in the PBR controller (robotcontroller_PBR.cpp @ line #307)  to get the measured angular velocity

**Comment by DomBaril** [comment]
If you want, I could do a pull request to show the changes I made to use the measured angular velocity in the controller.

**Comment by Gohus** [comment]
Hello @DomBaril, thank you for your feedback and all the support! And sorry for such a late reply!

Yes, you were right, we have somehow missed this line when we pushed the code. I have now corrected it in the repository (the same way you did).

Thanks and cheers!
