### ISSUE TITLE
Problems in simulation

### ISSUE THREAD

**Issue by Mr-Xavier** [cogsys-tuebingen/gerona#15]
Hi, thanks for your projects. I was just trying to test the navigation node in the stage and got  error like this:
**[ERROR] [1574837186.769389745, 1.000000000]: error transforming the obstacle cloud from base_link to map: the transformation between map and base_link does not exist.
[ WARN] [1574837187.368732183, 1.600000000]: cannot lookup relative transform from map to base_link at time 0.000000000. Using latest transform
[ WARN] [1574837187.468725955, 1.700000000]: cannot lookup relative transform from map to base_link at time 0.000000000. Using latest transform
[ WARN] [1574837187.670250319, 1.900000000]: cannot lookup relative transform from map to base_link at time 0.000000000. Using latest transform
[ WARN] [1574837187.770237280, 2.000000000]: cannot lookup relative transform from map to base_link at time 0.000000000. Using latest transform
[ WARN] [1574837187.870323464, 2.100000000]: cannot lookup relative transform from map to base_link at time 0.000000000. Using latest transform**
![屏幕截图 2019-11-27 14:51:33](https://user-images.githubusercontent.com/55989363/69700596-c4b6d500-1125-11ea-8f3e-a21c742a9c2a.png)
![屏幕截图 2019-11-27 14:52:09](https://user-images.githubusercontent.com/55989363/69700598-c84a5c00-1125-11ea-84cb-71df4345a788.png)
Can you give me some advice how to solve this problem.Thank you!

**Comment by betwo** [comment]
Hi @Mr-Xavier,

thank you for reaching out! Could you please give more details? Which launch file did you start?

Please also post your tf tree, e.g. as a screenshot of `rosrun rqt_tf_tree rqt_tf_tree`.

Cheers

**Comment by Xiewf123** [comment]
![frames](https://user-images.githubusercontent.com/20927712/69774490-03ee3000-11d1-11ea-814f-0e42c0d7331c.png)

**Comment by Mr-Xavier** [comment]
![frames](https://user-images.githubusercontent.com/55989363/69774705-ad352600-11d1-11ea-8907-5fcf5bf8a04a.png)

**Comment by Mr-Xavier** [comment]
> Hi @Mr-Xavier,
> 
> thank you for reaching out! Could you please give more details? Which launch file did you start?
> 
> Please also post your tf tree, e.g. as a screenshot of `rosrun rqt_tf_tree rqt_tf_tree`.
> 
> Cheers

![frames](https://user-images.githubusercontent.com/55989363/69858838-d76c0e00-12cd-11ea-850d-d9fbc6d8c6c0.png)

**Comment by Mr-Xavier** [comment]
@betwo 
![69774705-ad352600-11d1-11ea-8907-5fcf5bf8a04a](https://user-images.githubusercontent.com/55989363/69898565-1d8ca480-1396-11ea-9909-d99475544abb.png)

**Comment by betwo** [comment]
That actually looks fine. In the first few seconds, the transformation `map -> base_link` might not yet be published by `amcl`.

Did you send a navigation goal?

I reproduced the warnings (see https://youtu.be/y3L5xazTxf8) but the navigation still works.

**Comment by Mr-Xavier** [comment]
@betwo 
Thanks  for your reply. There are still some problems in the simulation. Sometimes it does not follow the planning path,  and  hits the obstacle directly.
![rviz_screenshot_2019_12_02-13_54_34](https://user-images.githubusercontent.com/55989363/69938222-ae3ebe00-1517-11ea-9429-bd57ddeac5fc.png)
![rviz_screenshot_2019_12_02-15_23_33](https://user-images.githubusercontent.com/55989363/69938252-c1518e00-1517-11ea-92b3-3fa5ae957f63.png)
![屏幕截图 2019-12-02 15:24:39](https://user-images.githubusercontent.com/55989363/69938298-e0502000-1517-11ea-93e0-2927429aae55.png)

**Comment by Mr-Xavier** [comment]
@betwo 
Thanks for your reply. There are still some problems in the simulation. Sometimes it does not follow the planning path, and hits the obstacle directly.
![rviz_screenshot_2019_12_02-13_54_34](https://user-images.githubusercontent.com/55989363/69939937-ff50b100-151b-11ea-92d4-71b8d9634a81.png)
![rviz_screenshot_2019_12_02-15_23_33](https://user-images.githubusercontent.com/55989363/69939946-01b30b00-151c-11ea-9698-0c7b4a14be22.png)
![屏幕截图 2019-12-02 15:24:39](https://user-images.githubusercontent.com/55989363/69939954-04adfb80-151c-11ea-9dab-537f1757ac31.png)

**Comment by betwo** [comment]
@Mr-Xavier sorry for the delay.

It looks like the selected controller started in the opposite direction somehow. I haven't observed this in the past.

Could you please specify under which circumstances this happens?
Also, which launch file did you use? 
Did you make customizations? If yes, which control algorithm is used?

Thanks!

**Comment by betwo** [comment]
Closed for inactivity. Please re-open if this is still an issue
