### ISSUE TITLE
is there any explanation for all the listed path planner algorithms and controllers?

### ISSUE THREAD

**Issue by zhurenjiek25** [cogsys-tuebingen/gerona#17]

**Comment by betwo** [comment]
Hi @zhurenjiek25,

thank you for reaching out. Please take a look at [https://github.com/cogsys-tuebingen/gerona/wiki/path-planner](the path planner) and the [https://github.com/cogsys-tuebingen/gerona/wiki/controllers](the controllers wiki page).

More information can be found in our [https://rdcu.be/barrQ](paper).

If you have any questions left, please open a new issue here about that specific topic.

Cheers
