### ISSUE TITLE
odom2tf failing 

### ISSUE THREAD

**Issue by michaelchi08** [cogsys-tuebingen/gerona#19]
Hello,

Thanks for this project.

System: ubuntu 16.x, ros kinetic

/home/michael/gerona_ws/src/gerona/tools/odom2tf/src/odom2tf_node.cpp: In function ‘int main(int, char**)’:
/home/michael/gerona_ws/src/gerona/tools/odom2tf/src/odom2tf_node.cpp:11:15: error: ISO C++ forbids declaration of ‘odom_frame’ with no type [-fpermissive]
   const auto& odom_frame = p_nh.param<std::string>("odom_frame", "odom");
               ^
/home/michael/gerona_ws/src/gerona/tools/odom2tf/src/odom2tf_node.cpp:11:51: error: invalid initialization of reference of type ‘const int&’ from expression of type ‘std::__cxx11::basic_string<char>’
   const auto& odom_frame = p_nh.param<std::string>("odom_frame", "odom");
                                                   ^
/home/michael/gerona_ws/src/gerona/tools/odom2tf/src/odom2tf_node.cpp:12:15: error: ISO C++ forbids declaration of ‘base_link_frame’ with no type [-fpermissive]
   const auto& base_link_frame = p_nh.param<std::string>("base_link_frame", "bas
               ^
/home/michael/gerona_ws/src/gerona/tools/odom2tf/src/odom2tf_node.cpp:12:56: error: invalid initialization of reference of type ‘const int&’ from expression of type ‘std::__cxx11::basic_string<char>’
   const auto& base_link_frame = p_nh.param<std::string>("base_link_frame", "bas
                                                        ^
/home/michael/gerona_ws/src/gerona/tools/odom2tf/src/odom2tf_node.cpp:28:7: warning: lambda expressions only available with -std=c++11 or -std=gnu++11
       };
       ^
/home/michael/gerona_ws/src/gerona/tools/odom2tf/src/odom2tf_node.cpp:28:7: error: conversion from ‘main(int, char**)::<lambda(const ConstPtr&)>’ to non-scalar type ‘boost::function<void(const boost::shared_ptr<const nav_msgs::Odometry_<std::allocator<void> > >&)>’ requested
/home/michael/gerona_ws/src/gerona/tools/odom2tf/src/odom2tf_node.cpp:30:8: error: ‘sub’ does not name a type
   auto sub = nh.subscribe<nav_msgs::Odometry>("odom", 10, callback);
        ^
[ 69%] Building CXX object gerona/path_planner/CMakeFiles/course_planner_node.dir/src/course_planner/course/node.cpp.o
[ 70%] Building CXX object gerona/path_planner/CMakeFiles/course_planner_node.dir/src/course_planner/course/course_map.cpp.o
gerona/tools/odom2tf/CMakeFiles/odom2tf_node.dir/build.make:62: recipe for target 'gerona/tools/odom2tf/CMakeFiles/odom2tf_node.dir/src/odom2tf_node.cpp.o' failed
make[2]: *** [gerona/tools/odom2tf/CMakeFiles/odom2tf_node.dir/src/odom2tf_node.cpp.o] Error 1
CMakeFiles/Makefile2:3080: recipe for target 'gerona/tools/odom2tf/CMakeFiles/odom2tf_node.dir/all' failed
make[1]: *** [gerona/tools/odom2tf/CMakeFiles/odom2tf_node.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

Can you please help me figure out this error building this node?

Thanks,
Michael

**Comment by betwo** [comment]
Hi @michaelchi08,

thanks for reporting this. It seems like we did not ensure that `odom2tf` is compiled with the C++11 standard.
This causes the `auto` not to be interpreted correctly in `odom2tf_node.cpp:11:15`.

I opened a pull request (#20) that should fix this. Could you please check if that works for you?

**Comment by betwo** [comment]
#20 is merged now. If that does not fix this problem, please re-open this issue.
