### ISSUE TITLE
Broken link/private link - from https://github.com/cogsys-tuebingen/gerona to https://gitlab.cs.uni-tuebingen.de/apps/navigation/wikis/home

### ISSUE THREAD

**Issue by willchamberlain** [cogsys-tuebingen/gerona#2]
Hello

So you know: the link from https://github.com/cogsys-tuebingen/gerona to https://gitlab.cs.uni-tuebingen.de/apps/navigation/wikis/home is broken/private: 

- https://gitlab.cs.uni-tuebingen.de/apps/navigation/wikis/home forwards to https://gitlab.cs.uni-tuebingen.de/users/sign_in
- non-SSL http://gitlab.cs.uni-tuebingen.de/apps/navigation/wikis/home does not respond.

Regards,
Will

**Comment by betwo** [comment]
Thanks for the hint!
