### ISSUE TITLE
gerona package fail to build on Jetson Tx2 because gcc version on arm platform doesn't include mm_malloc.h

### ISSUE THREAD

**Issue by michaelchi08** [cogsys-tuebingen/gerona#23]
Is there a work around for this? Is there a way i could copy this to a gcc path or something?

home/nvidia/catkin_ws/src/gerona/tools/model_based_planner/include/model_based_planner/cv_aligned_mat.h:5:23: fatal error: **mm_malloc.h: No such file or directory**
compilation terminated.
gerona/tools/model_based_planner/CMakeFiles/model_based_planner.dir/build.make:62: recipe for target 'gerona/tools/model_based_planner/CMakeFiles/model_based_planner.dir/src/wheelmodel.cpp.o' failed
make[2]: *** [gerona/tools/model_based_planner/CMakeFiles/model_based_planner.dir/src/wheelmodel.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[  0%] Building CXX object gerona/tools/model_based_planner/CMakeFiles/model_based_planner.dir/src/robotmodel.cpp.o
[  0%] Built target nav_msgs_generate_messages_lisp
In file included from /home/nvidia/catkin_ws/src/gerona/tools/model_based_planner/include/model_based_planner/wheeldescriptor.h:4:0,
                 from /home/nvidia/catkin_ws/src/gerona/tools/model_based_planner/include/model_based_planner/wheelmodel.h:4,
                 from /home/nvidia/catkin_ws/src/gerona/tools/model_based_planner/include/model_based_planner/robotmodel.h:4,
                 from /home/nvidia/catkin_ws/src/gerona/tools/model_based_planner/include/model_based_planner/poseestimator.h:6,
                 from /home/nvidia/catkin_ws/src/gerona/tools/model_based_planner/src/poseestimator.cpp:1:
/home/nvidia/catkin_ws/src/gerona/tools/model_based_planner/include/model_based_planner/cv_aligned_mat.h:5:23: fatal error: mm_malloc.h: No such file or directory
compilation terminated.
gerona/tools/model_based_planner/CMakeFiles/model_based_planner.dir/build.make:86: recipe for target 'gerona/tools/model_based_planner/CMakeFiles/model_based_planner.dir/src/poseestimator.cpp.o' failed
make[2]: *** [gerona/tools/model_based_planner/CMakeFiles/model_based_planner.dir/src/poseestimator.cpp.o] Error 1
In file included from /home/nvidia/catkin_ws/src/gerona/tools/model_based_planner/include/model_based_planner/chassisdescriptor.h:4:0,
                 from /home/nvidia/catkin_ws/src/gerona/tools/model_based_planner/include/model_based_planner/chassismodel.h:5,
                 from /home/nvidia/catkin_ws/src/gerona/tools/model_based_planner/src/chassismodel.cpp:1:
/home/nvidia/catkin_ws/src/gerona/tools/model_based_planner/include/model_based_planner/cv_aligned_mat.h:5:23: fatal error: mm_malloc.h: No such file or directory
compilation terminated.
gerona/tools/model_based_planner/CMakeFiles/model_based_planner.dir/build.make:134: recipe for target 'gerona/tools/model_based_planner/CMakeFiles/model_based_planner.dir/src/chassismodel.cpp.o' failed
make[2]: *** [gerona/tools/model_based_planner/CMakeFiles/model_based_planner.dir/src/chassismodel.cpp.o] Error 1
In file included from /home/nvidia/catkin_ws/src/gerona/tools/model_based_planner/include/model_based_planner/wheeldescriptor.h:4:0,
                 from /home/nvidia/catkin_ws/src/gerona/tools/model_based_planner/include/model_based_planner/wheelmodel.h:4,
                 from /home/nvidia/catkin_ws/src/gerona/tools/model_based_planner/include/model_based_planner/robotmodel.h:4,
                 from /home/nvidia/catkin_ws/src/gerona/tools/model_based_planner/src/robotmodel.cpp:1:
/home/nvidia/catkin_ws/src/gerona/tools/model_based_planner/include/model_based_planner/cv_aligned_mat.h:5:23: fatal error: mm_malloc.h: No such file or directory
compilation terminated.
gerona/tools/model_based_planner/CMakeFiles/model_based_planner.dir/build.make:158: recipe for target 'gerona/tools/model_based_planner/CMakeFiles/model_based_planner.dir/src/robotmodel.cpp.o' failed
make[2]: *** [gerona/tools/model_based_planner/CMakeFiles/model_based_planner.dir/src/robotmodel.cpp.o] Error 1
CMakeFiles/Makefile2:551: recipe for target 'gerona/tools/model_based_planner/CMakeFiles/model_based_planner.dir/all' failed
make[1]: *** [gerona/tools/model_based_planner/CMakeFiles/model_based_planner.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[  0%] Built target geometry_msgs_generate_messages_lisp
[  0%] Built target _path_msgs_generate_messages_check_deps_FollowerOptions
[  0%] Built target _path_msgs_generate_messages_check_deps_Goal
[  0%] Built target _path_msgs_generate_messages_check_deps_NavigateToGoalFeedback
[  0%] Built target _path_msgs_generate_messages_check_deps_PlanPathGoal
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j6 -l6" failed

**Comment by betwo** [comment]
Since this is part of the model_based_planner, can you take a look at this @jquadrat?

**Comment by jquadrat** [comment]
The mm_alloc.h header now is only included when SSE4.2 or AVX2 are available (otherwise the memory alignment is not needed). Assuming the TX2 has no SSE or AVX this should fix the problem. Unfortunately I didn't have an ARM system to test it.

**Comment by betwo** [comment]
Closing this for now. Please re-open if this is still a problem
