### ISSUE TITLE
pure rotation motion

### ISSUE THREAD

**Issue by arenas7307979** [cogsys-tuebingen/gerona#25]
hii, 
I  run successfully the concept API (follow_path_example.py)  to the actual differential  robot scenario.

This API only considers the status of my planning position, and it seems that the rotation angle does not affect the control. (position and rotation from the nav_path)

I had some problems,  when the rotation angle is too large and my robot not allow reverse motion that  resulting in uncontrollable situations (robot cannot turn at the right Angle).

I want to use pure rotational motion to solve this problem
Is there any way to using command in the API to make the robot do pure rotation?

Thank you for your kind assistance.

**Comment by betwo** [comment]
Sorry for the delay, I totally missed this issue..

We don't provide an API for pure rotation. 
However, as the stack relies uses `cmd_vel` to control the robot,  you can use this to perform a rotation yourself by sending a linear velocity of `(0, 0, 0)` and an angular velocity of `(0,0, \omega)` for any angular velocity `\omega`.
