### ISSUE TITLE
no dynplanner.launch?

### ISSUE THREAD

**Issue by zouyonghao** [cogsys-tuebingen/gerona#27]
It seems no `dynplanner.launch`

https://github.com/cogsys-tuebingen/gerona/blob/d0d7dd37a93f210c7f9a06c91f1f310c47079f45/path_planner/launch/path_planner.launch#L25

**Comment by betwo** [comment]
Sorry for the massive delay.
Good catch, the corresponding planner type has been deleted a while back.
Will remove the option soon.

**Comment by betwo** [comment]
The option is no longer available.
