### ISSUE TITLE
undefined reference to "alglib"

### ISSUE THREAD

**Issue by Ruanpe** [cogsys-tuebingen/gerona#29]
/home/ruanpe/project/ros/GeRoNa/devel/lib/libpath_follower.so：undefined reference to ‘alglib::spline1dconvdiff2cubic(alglib::real_1d_array const&, alglib::real_1d_array const&, alglib::real_1d_array const&, alglib::real_1d_array&, alglib::real_1d_array&, alglib::real_1d_array&, alglib::xparams)’
/home/ruanpe/project/ros/GeRoNa/devel/lib/libpath_follower.so：undefined reference to‘alglib::real_1d_array::real_1d_array()’
/home/ruanpe/project/ros/GeRoNa/devel/lib/libpath_follower.so：undefined reference to‘alglib::real_1d_array::operator[](long)’
/home/ruanpe/project/ros/GeRoNa/devel/lib/libpath_follower.so：undefined reference to‘alglib::real_1d_array::~real_1d_array()’
/home/ruanpe/project/ros/GeRoNa/devel/lib/libpath_follower.so：undefined reference to‘alglib::real_1d_array::setcontent(long, double const*)’
/home/ruanpe/project/ros/GeRoNa/devel/lib/libpath_follower.so：undefined reference to ‘alglib::xdefault’ collect2: error: ld returned 1 exit status
gerona/path_follower/CMakeFiles/path_follower_node.dir/build.make:713: recipe for target '/home/ruanpe/project/ros/GeRoNa/devel/lib/path_follower/path_follower_node' failed
make[2]: *** [/home/ruanpe/project/ros/GeRoNa/devel/lib/path_follower/path_follower_node] Error 1
CMakeFiles/Makefile2:6757: recipe for target 'gerona/path_follower/CMakeFiles/path_follower_node.dir/all' failed
make[1]: *** [gerona/path_follower/CMakeFiles/path_follower_node.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j4 -l4" failed

**Comment by betwo** [comment]
Hi @Ruanpe, could you please give a little bit of context?
Which ubuntu + ROS combination are you using? 
Did running `rosdep install` show any errors?
Specifically, did the installation of `libalglib-dev` succeed?

**Comment by Ruanpe** [comment]
> Hi @Ruanpe, could you please give a little bit of context?
> Which ubuntu + ROS combination are you using?
> Did running `rosdep install` show any errors?
> Specifically, did the installation of `libalglib-dev` succeed?

>Hi@betwo, Thanks for your opensource.
> Ubuntu  16.04 +  kinetic is my using.
>When I use `rosdep install`,there is no errors.
>`libalglib-dev`has been installed successfully.
>when I used `sudo apt-get install libalglib-dev`,`libalglib-dev` shows the latest version.

**Comment by betwo** [comment]
Thank you for the update.
I tried to reproduce this in a fresh docker file with Ubuntu 16 and ROS kinetic.
There is currently a bug in the `perception_pcl` package which causes a build failure in this version combination.
Cloning `github.com:ros-perception/perception_pcl.git` locally I get a successful build, though.

Could you please attach the full build logs? Maybe we can find the difference in your setup.

**Comment by Ruanpe** [comment]
>Sorry, I don't understand which information you want me to submit.
>I'm not sure if you want the build logs from  `perception_pcl` or `gerona`.
>In addition, cloning `https://github.com/S-Dafarra/alglib-cmake.git` locally I downloaded and compiled successfully.I guess it's the problem of the alglib version.

>`perception_pcl` get a successful build.
>When I use catkin_build_isolated, the following is the build logs.
>If none of this information is what you are looking for, I can provide additional information. 

>==> Processing catkin package: 'path_follower'
==> Building with env: '/home/ruanpe/project/ros/GeRoNa/devel_isolated/path_control/env.sh'
Makefile exists, skipping explicit cmake invocation...
==> make cmake_check_build_system in '/home/ruanpe/project/ros/GeRoNa/build_isolated/path_follower'
==> make -j4 -l4 in '/home/ruanpe/project/ros/GeRoNa/build_isolated/path_follower'
[  0%] Built target topic_tools_generate_messages_lisp
[  2%] Built target pose_goal_remapper
[  2%] Built target topic_tools_generate_messages_py
[  2%] Built target std_srvs_generate_messages_cpp
[  2%] Built target topic_tools_generate_messages_eus
[  2%] Built target nav_msgs_generate_messages_lisp
[  2%] Built target std_srvs_generate_messages_nodejs
[  2%] Built target std_srvs_generate_messages_lisp
[  2%] Built target roscpp_generate_messages_eus
[  2%] Built target trajectory_msgs_generate_messages_cpp
[  2%] Built target tf_generate_messages_py
[  2%] Built target std_msgs_generate_messages_nodejs
[  2%] Built target bond_generate_messages_eus
[  2%] Built target control_msgs_generate_messages_cpp
[  2%] Built target roscpp_generate_messages_py
[  2%] Built target std_srvs_generate_messages_py
[  2%] Built target tf_generate_messages_nodejs
[  2%] Built target actionlib_generate_messages_lisp
[  2%] Built target actionlib_msgs_generate_messages_eus
[  2%] Built target rosgraph_msgs_generate_messages_eus
[  2%] Built target path_msgs_generate_messages_py
[  2%] Built target std_msgs_generate_messages_py
[  2%] Built target path_msgs_generate_messages_cpp
[  2%] Built target path_msgs_generate_messages_eus
[  2%] Built target nav_msgs_generate_messages_nodejs
[  2%] Built target nav_msgs_generate_messages_py
[  2%] Built target actionlib_msgs_generate_messages_nodejs
[  2%] Built target path_msgs_generate_messages_nodejs
[  2%] Built target tf2_msgs_generate_messages_py
[  2%] Built target actionlib_generate_messages_cpp
[  2%] Built target rosgraph_msgs_generate_messages_lisp
[  2%] Built target sensor_msgs_generate_messages_py
[  2%] Built target roscpp_generate_messages_nodejs
[  2%] Built target pcl_msgs_generate_messages_nodejs
[  2%] Built target topic_tools_generate_messages_nodejs
[  2%] Built target sensor_msgs_generate_messages_lisp
[  2%] Built target actionlib_msgs_generate_messages_cpp
[  2%] Built target sensor_msgs_generate_messages_eus
[  2%] Built target actionlib_msgs_generate_messages_lisp
[  2%] Built target geometry_msgs_generate_messages_py
[  2%] Built target geometry_msgs_generate_messages_lisp
[  2%] Built target bond_generate_messages_py
[  2%] Built target std_msgs_generate_messages_lisp
[  2%] Built target rosgraph_msgs_generate_messages_nodejs
[  2%] Built target path_msgs_generate_messages_lisp
[  2%] Built target actionlib_generate_messages_eus
[  2%] Built target std_msgs_generate_messages_eus
[  2%] Built target tf_generate_messages_cpp
[  2%] Built target std_srvs_generate_messages_eus
[  2%] Built target rosgraph_msgs_generate_messages_cpp
[  2%] Built target pcl_msgs_generate_messages_eus
[  2%] Built target geometry_msgs_generate_messages_nodejs
[  2%] Built target geometry_msgs_generate_messages_eus
[  2%] Built target roscpp_generate_messages_cpp
[  2%] Built target nodelet_generate_messages_py
[  2%] Built target actionlib_msgs_generate_messages_py
[  2%] Built target nav_msgs_generate_messages_cpp
[  2%] Built target geometry_msgs_generate_messages_cpp
[  2%] Built target std_msgs_generate_messages_cpp
[  2%] Built target nav_msgs_generate_messages_eus
[  2%] Built target roscpp_generate_messages_lisp
[  2%] Built target _catkin_empty_exported_target
[  2%] Built target control_msgs_generate_messages_eus
[  2%] Built target control_msgs_generate_messages_lisp
[  2%] Built target trajectory_msgs_generate_messages_lisp
[  2%] Built target dynamic_reconfigure_generate_messages_nodejs
[  2%] Built target control_msgs_generate_messages_nodejs
[  2%] Built target actionlib_generate_messages_nodejs
[  2%] Built target control_msgs_generate_messages_py
[  2%] Built target nodelet_topic_tools_gencfg
[  2%] Built target trajectory_msgs_generate_messages_eus
[  2%] Built target trajectory_msgs_generate_messages_nodejs
[  2%] Built target trajectory_msgs_generate_messages_py
[  2%] Built target tf_generate_messages_eus
[  2%] Built target sensor_msgs_generate_messages_cpp
[  2%] Built target sensor_msgs_generate_messages_nodejs
[  2%] Built target tf2_msgs_generate_messages_cpp
[  2%] Built target pcl_ros_gencfg
[  2%] Built target tf2_msgs_generate_messages_eus
[  2%] Built target nodelet_generate_messages_cpp
[  2%] Built target tf2_msgs_generate_messages_lisp
[  2%] Built target tf2_msgs_generate_messages_nodejs
[  2%] Built target topic_tools_generate_messages_cpp
[  2%] Built target nodelet_generate_messages_eus
[  2%] Built target dynamic_reconfigure_generate_messages_cpp
[  2%] Built target pcl_msgs_generate_messages_py
[  2%] Built target bond_generate_messages_nodejs
[  2%] Built target dynamic_reconfigure_generate_messages_eus
[  2%] Built target dynamic_reconfigure_generate_messages_lisp
[  2%] Built target actionlib_generate_messages_py
[  2%] Built target dynamic_reconfigure_generate_messages_py
[  2%] Built target dynamic_reconfigure_gencfg
[  2%] Built target nodelet_generate_messages_lisp
[  2%] Built target nodelet_generate_messages_nodejs
[  2%] Built target bond_generate_messages_cpp
[  2%] Built target bond_generate_messages_lisp
[  2%] Built target pcl_msgs_generate_messages_lisp
[  2%] Built target pcl_msgs_generate_messages_cpp
[  4%] Built target test_output_2_csv
Scanning dependencies of target path_follower
[  5%] Building CXX object CMakeFiles/path_follower.dir/src/utils/path_interpolated.cpp.o
[  6%] Linking CXX shared library /home/ruanpe/project/ros/GeRoNa/devel_isolated/path_follower/lib/libpath_follower.so
[ 97%] Built target path_follower
[ 97%] Built target rosgraph_msgs_generate_messages_py
[ 97%] Built target tf_generate_messages_lisp
[ 98%] Linking CXX executable /home/ruanpe/project/ros/GeRoNa/devel_isolated/path_follower/lib/path_follower/path_follower_node
/home/ruanpe/project/ros/GeRoNa/devel_isolated/path_follower/lib/libpath_follower.so：undefined reference to ‘alglib::spline1dconvdiff2cubic(alglib::real_1d_array const&, alglib::real_1d_array const&, alglib::real_1d_array const&, alglib::real_1d_array&, alglib::real_1d_array&, alglib::real_1d_array&, alglib::xparams)’
/home/ruanpe/project/ros/GeRoNa/devel_isolated/path_follower/lib/libpath_follower.so：undefined reference to ‘alglib::real_1d_array::real_1d_array()’
/home/ruanpe/project/ros/GeRoNa/devel_isolated/path_follower/lib/libpath_follower.so：undefined reference to ‘alglib::real_1d_array::operator[](long)’
/home/ruanpe/project/ros/GeRoNa/devel_isolated/path_follower/lib/libpath_follower.so：undefined reference to ‘alglib::real_1d_array::~real_1d_array()’
/home/ruanpe/project/ros/GeRoNa/devel_isolated/path_follower/lib/libpath_follower.so：undefined reference to ‘alglib::real_1d_array::setcontent(long, double const*)’
/home/ruanpe/project/ros/GeRoNa/devel_isolated/path_follower/lib/libpath_follower.so：undefined reference to ‘alglib::xdefault’
collect2: error: ld returned 1 exit status
CMakeFiles/path_follower_node.dir/build.make:732: recipe for target '/home/ruanpe/project/ros/GeRoNa/devel_isolated/path_follower/lib/path_follower/path_follower_node' failed
make[2]: *** [/home/ruanpe/project/ros/GeRoNa/devel_isolated/path_follower/lib/path_follower/path_follower_node] Error 1
CMakeFiles/Makefile2:235: recipe for target 'CMakeFiles/path_follower_node.dir/all' failed
make[1]: *** [CMakeFiles/path_follower_node.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
<== Failed to process package 'path_follower': 
  Command '['/home/ruanpe/project/ros/GeRoNa/devel_isolated/path_control/env.sh', 'make', '-j4', '-l4']' returned non-zero exit status 2

Reproduce this error by running:
==> cd /home/ruanpe/project/ros/GeRoNa/build_isolated/path_follower && /home/ruanpe/project/ros/GeRoNa/devel_isolated/path_control/env.sh make -j4 -l4

Command failed, exiting.

**Comment by betwo** [comment]
Thank you for the update!

> In addition, cloning https://github.com/S-Dafarra/alglib-cmake.git locally I downloaded and compiled successfully.I guess it's the problem of the alglib version.

Do you mean `alglib` compiled successfully, or the complete workspace including `gerona`?
If `gerona` builds with the manual checkout, then that's strange - the CI build worked with the latest apt-version of `alglib`.

In that case, we could take a look at the verbose build output to check what is different about your setup.
What's the output of the following?
```bash
cd <workspace>/build/path_follower
make clean
VERBOSE=1 make 
```
I'd be specifically interested in the call to the linker here

**Comment by Ruanpe** [comment]
> No changes have been made to the location of alglib in gerona's CmakeLists. The following is the build logs.

> ```shell
> /home/ruanpe/project/ros/test_ws/devel/lib/libpath_follower.so：undefined reference to ‘alglib::spline1dconvdiff2cubic(alglib::real_1d_array const&, alglib::real_1d_array const&, alglib::real_1d_array const&, alglib::real_1d_array&, alglib::real_1d_array&, alglib::real_1d_array&, alglib::xparams)’
> /home/ruanpe/project/ros/test_ws/devel/lib/libpath_follower.so：undefined reference to‘alglib::xdefault’
> collect2: error: ld returned 1 exit status
> gerona/path_follower/CMakeFiles/path_follower_node.dir/build.make:713: recipe for target '/home/ruanpe/project/ros/test_ws/devel/lib/path_follower/path_follower_node' failed
> make[2]: *** [/home/ruanpe/project/ros/test_ws/devel/lib/path_follower/path_follower_node] Error 1
> CMakeFiles/Makefile2:7238: recipe for target 'gerona/path_follower/CMakeFiles/path_follower_node.dir/all' failed
> make[1]: *** [gerona/path_follower/CMakeFiles/path_follower_node.dir/all] Error 2
> Makefile:138: recipe for target 'all' failed
> make: *** [all] Error 2
> Invoking "make -j4 -l4" failed
> ```

> When I change the location of alglib in gerona's CmakeLists, the following is the build logs.

> The following are the changes in CmakeLists.
> ```shell
> find_package(PCL REQUIRED)
> #find_package(ALGLIB REQUIRED)
> find_package(Eigen3 REQUIRED)
> find_package(OpenCV REQUIRED)
> set(ALGLIB_DIR "/usr/include/vtk-6.2/alglib")
> set(ALGLIB_LIB "/usr/lib/x86_64-linux-gnu/libvtkalglib-6.2.so")
> ```
> The following is the build logs. Same as the output compiled by `make clean`, `VERBOSE=1 make`.

> ```shell
> /home/ruanpe/project/ros/GeRoNa/devel_isolated/path_follower/lib/libpath_follower.so：undefined reference to ‘alglib::spline1dconvdiff2cubic(alglib::real_1d_array const&, alglib::real_1d_array const&, alglib::real_1d_array const&, alglib::real_1d_array&, alglib::real_1d_array&, alglib::real_1d_array&, alglib::xparams)’
> /home/ruanpe/project/ros/GeRoNa/devel_isolated/path_follower/lib/libpath_follower.so：undefined reference to ‘alglib::real_1d_array::real_1d_array()’
> /home/ruanpe/project/ros/GeRoNa/devel_isolated/path_follower/lib/libpath_follower.so：undefined reference to ‘alglib::real_1d_array::operator’
> /home/ruanpe/project/ros/GeRoNa/devel_isolated/path_follower/lib/libpath_follower.so：undefined reference to ‘alglib::real_1d_array::~real_1d_array()’
> /home/ruanpe/project/ros/GeRoNa/devel_isolated/path_follower/lib/libpath_follower.so：undefined reference to ‘alglib::real_1d_array::setcontent(long, double const*)’
> /home/ruanpe/project/ros/GeRoNa/devel_isolated/path_follower/lib/libpath_follower.so：undefined reference to ‘alglib::xdefault’
> collect2: error: ld returned 1 exit status
> CMakeFiles/path_follower_node.dir/build.make:732: recipe for target '/home/ruanpe/project/ros/GeRoNa/devel_isolated/path_follower/lib/path_follower/path_follower_node' failed
> make[2]: *** [/home/ruanpe/project/ros/GeRoNa/devel_isolated/path_follower/lib/path_follower/path_follower_node] Error 1
> CMakeFiles/Makefile2:235: recipe for target 'CMakeFiles/path_follower_node.dir/all' failed
> make[1]: *** [CMakeFiles/path_follower_node.dir/all] Error 2
> Makefile:138: recipe for target 'all' failed
> make: *** [all] Error 2
> ```shell

**Comment by betwo** [comment]
Sorry for the delay. 

Is that the full output? I would expect some invocation of `ld` and `gcc` in there.

Overall, this looks like a version mismatch of `alglib`. I can image that this fails because you have multiple versions installed and the cmake find script for alglib finds the headers of a different version than the detected binaries.
That's why I was asking about the verbose log, there we should see both the compiler and the linker invocations with your system paths for the `alglib` files.
(You don't have to add the full log, you can also extract those paths yourself ;) )

**Comment by Ruanpe** [comment]
Thanks, I have solved this problem.
When I used `sudo make uninstall`，`alglib-cmake` was unloaded.
This repository was compiled successfully.

**Comment by betwo** [comment]
A nice, good to hear!

**Comment by kangkelvin** [comment]
Hi, I am facing the same issue. Can you outline step by step how to resolve it? Thanks

**Comment by betwo** [comment]
Hi @kangkelvin, 

are you also using Ubuntu 16 / ROS kinetic? Since September 20th the GitHub CI no longer supports this legacy release, but up to that point the build on a clean docker image was successful: https://github.com/cogsys-tuebingen/gerona/actions/runs/1251828894.
From what I understood, the original problem was a custom version of alglib that was installed in the system.

Did you already try the steps above, i.e.
- Checking which versions of `alglib` are installed on your machine?
- Checking with `VERBOSE=1 make` which binary of `alglib` cmake is linking against?
- (Possibly compiling `github.com:ros-perception/perception_pcl.git` by hand)

**Comment by betwo** [comment]
Closing this to clean up old issues.
