### ISSUE TITLE
Is there some demos can running offline?

### ISSUE THREAD

**Issue by gongyue666** [cogsys-tuebingen/gerona#3]
hi, thanks for you project.I want to  ask is there some demo that can be used offline in rviz ,not in a real robot.By the way, there are some bugs in path_planner will make catkin_make error.

**Comment by betwo** [comment]
Hi, thank you for the feedback.


_Offline testing:_
To test the stack offline, you need to set up a simulator. We have used gazebo and stage in the past.
For example, we have used http://wiki.ros.org/summit_xl_sim in Gazebo (http://wiki.ros.org/simulator_gazebo/Tutorials/StartingGazebo).

Everything should work just as on a real robot (see the main [README.md file under Quick Start](https://github.com/cogsys-tuebingen/gerona#quick-start))


_Build Errors:_
I have just pushed the latest version, which builds on our continuous integration server with a clean ROS docker from indigo up to melodic.

Does the error still occur for you? Could you then please create a new issue and elaborate on the build error? That is, which ROS version are you using? Which Ubuntu version? What is the error message?
Thank you.

**Comment by betwo** [comment]
There are now also demo launch files in the repository (gerona_examples)
