### ISSUE TITLE
Using follower only with hbz，The max velocity in X direction is only about 0.35m/s

### ISSUE THREAD

**Issue by FProgrammerLIU** [cogsys-tuebingen/gerona#30]
hello. 
when using follower only with hbz，a linear path with a step size of 0.2m, the max velocity in X direction is only about 0.35m/s, i try all the params, but without effect.
Hope to give me some reasons and suggestions, thanks so much.

**Comment by betwo** [comment]
Hi @FProgrammerLIU,

could you  please set the logging level to `DEBUG` and check for output of the form
```log
velocity: ____, vn: ____
```
to further debug this?
This is the desired velocity of the controller. 

Other factors can slow down the robot as well, but that is hard to judge without further context:
* Are you using a simulator?
* How long are the paths you are testing?
* Are you using obstacle detection / collision avoidance? This can slow down the robot in the vicinity of obstacles.
* Is the maximum speed set close to 0.35m/s?
* Is the path short? Velocity control slows down the robot when it reaches the path endpoint.

**Comment by betwo** [comment]
Closing this to clean up old issues.
