### ISSUE TITLE
report bug in my computer

### ISSUE THREAD

**Issue by gongyue666** [cogsys-tuebingen/gerona#4]
Hi, I modify sbpl_planner_node.cpp line46 from :
return type == path_msgs::PlanPathGoal::GOAL_TYPE_POSE;
to 
return type == path_msgs::Goal::GOAL_TYPE_POSE;
and  when I install ompl-app, it took some long time, must the ompl-app be used?How about using just ompl instead?
my system is Ubuntu 16.04 ROS Kinetic.
By the way, could you give some easy ways to test,like teb_local_planner_tutorial or use rosbag to supply the needed topics, gazebo always has some questions for me.
Thx for your job, I am learning about the code, but till now I can't run it or see some results~

**Comment by betwo** [comment]
@gongyue666 Thank you for the report.

The (optional and experimental) SBPL planner was not maintained anymore, but should now work again. From now on it is also tested in our CI-chain.

As to the OMPL planner: The planner is also very experimental and never provided satisfying results for us. The app-part is needed for the KinematicCarPlanning class.
If you need pure OMPL support, please feel free to open a pull-request!

For the last point, I created issue #5.
