### ISSUE TITLE
Help: Trying to use this package to make a differential drive mobile robot follow a curved path

### ISSUE THREAD

**Issue by vannem95** [cogsys-tuebingen/gerona#6]
Hi,

My current setup is a differential drive mobile base which takes command velocity. I get the pose of the robot using aruco_mapping. I got ros's navigation to work but i couldn't move it on a curved path(it only does turn and go motion).

Is it possible to use gerona to make my bot follow a curved path? If so, what is the easiest way to do it?

Thanks in advance

**Comment by Gohus** [comment]
Hello vannem95,

yes, GeRoNa allows you to plan and follow any path with arbitrary curvature. And a differential drive is supported with several different controllers.

Perhaps the easiest way would be to try out these simple examples provided by betwo: [gerona examples](https://github.com/cogsys-tuebingen/gerona/tree/master/gerona_examples).

To use a differential drive controller, you can choose any of the compatible controllers from the table provided [here](https://github.com/cogsys-tuebingen/gerona/wiki/controllers).

I hope this helps. If you have any further questions, just let us know!
